apiVersion: v1
kind: Pod
metadata:
  name: pod-sidecar
  labels:
    app: nginx-sidecar
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: html-sidecar
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from sidecar > /pod-data/index.html; sleep 100000"]
