apiVersion: v1
kind: Pod
metadata:
  name: mylimitedpod
spec:
  containers:
  - name: mypod1
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
