apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  volumes:
  - name: vol1
    configMap:
      name: myconfigmap
  containers:
  - name: mypod1
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /usr/share/nginx/html